version: '3.8'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: cds_hooks_ms
    container_name: hooks_manager_service
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
    #mongodb container name
      - MONGODB_HOST=mongodb
      #mongodb container port numnber
      - MONGODB_PORT=27017
      #collection name for logs
      - MONGODB_LOGS=hooks_ms_log
      #name of CIG formalism involved 
      #(as there could be more than one distinct formalism).
      #This is also the name of the MongoDB collection to store
      #hook processing documents associated with this formalism
      - MONGODB_CIG_MODEL=tmr
      #name of mongoDB collection for processing hooks which
      #do not access TMR knowledge (or any other formalism) to
      #produce a result
      - MONGODB_NONCIG_DB_NAME=non-cig
      #name of cds services manager container and associted port
      - CDS_SERVICES_MS_HOST=services_manager_service
      - CDS_SERVICES_MS_PORT=3010
      #URL of SNOMED CT server
      - SNOMEDCT_BASE_URL=snowstorm-fhir.snomedtools.org
      #Port number of this microservice
      - PROXY_PORT=3000
    links:
      - db
    depends_on:
      - db
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports: 
        - "27012:27017"
    container_name: mongodb
    volumes:
      - ~/mongodata:/data/db
    networks:
      - dmims
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports: 
    - '8083:8081'
    networks:
    - dmims
  busybox:
    image: busybox
    container_name: fuseki-data
    #restart: unless-stopped
    networks: 
      - cig_handler
    volumes: 
      - "drug_volume:/fuseki_store"
  fuseki_store:
    build: 
      context: ./TMRWebX/fuseki/
      dockerfile: Dockerfile
    image: fuseki_store
    container_name: store_ms
    restart: unless-stopped
    #expose: 3030
    ports: 
      - "3030:3030"
    networks: 
      - cig_handler
    #volumes_from: 
    #  - drug_volume
    environment:
      - ADMIN_PASSWORD=road2h
      - TDB=2
      - FUSEKI_DATASET_1=careActions
      - FUSEKI_DATASET_2=transitions
      - FUSEKI_DATASET_3=beliefs
      - FUSEKI_DATASET_4=CIG-COPD
      - JVM_ARGS=-Xmx2g
    depends_on: 
      - busybox

  interaction_app:
    build: 
      context: ./TMRWebX/api/
      dockerfile: Dockerfile
    image: interaction_ms
    container_name: interaction_ms
    restart: unless-stopped
    #expose: 
    #  - 8888
    ports:
      - "8888:8888"
    networks: 
      - cig_handler
    environment:
      - JENA_HOST=fuseki
      - PROLOG_HOST=swipl
      - JENA_PORT=3030
      - PROLOG_PORT=1234
      - PORT=8888
      - FUSEKI_PASSWORD=road2h
    depends_on:
      - reasoner_app
  reasoner_app:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    image: road2h-swipl
    container_name: swipl
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #expose:
    #  - 1234
    ports: 
      - "1234:1234"
    networks: 
      - cig_handler
    environment:
      - FUSEKI_HOST_PORT=http://fuseki:3030/
    depends_on: 
      - fuseki
volumes:
  drug_volume: {}
networks:
  cig_handler: {}
  dmims: {}
  #tmrwebx_cig_handler:
   # external: true
#volumes: 
 # - ~/mongodata: